### ISSUE TITLE
一个莫名其妙的issue - 请看详情~

### ISSUE THREAD

**Issue by amchii** [Summyj/Summyj.github.io#24]
**以下按顺序描述**

我在使用青藤之恋小程序时，发现想要查看别人资料必须要点进去（这不废话么）留下访问足迹，但是如果分享给别人，那么被分享人如果没有注册的话也是可以查看的，应该也不会有什么足迹留下。其中有个让我别扭的点是在喜欢界面可以直接点击超级喜欢，取消喜欢/超级喜欢却要进入别人主页下划到末尾才可以！也就是说取消喜欢/超级喜欢同样会留下访问足迹，怎么说呢就是这个有点别扭。

于是我想抓包看看青藤的接口有没有破绽，按照习惯（不是。）先上github搜索有没有相关信息，以”青藤之恋“为关键词搜索，没发现有相关的仓库，在code一栏，我发现了
![image](https://user-images.githubusercontent.com/26922464/173795832-11a6454e-5036-407c-87bc-de3f3f62e9dd.png)
本仓库的一篇文章，然后顺藤摸瓜地到了你的个人博客把相关文章看了个遍。。原来是为同岁的程序媛？然后感觉比较有意思，想在博客评论的，但想着唉我本就是在github上看到的，还是通过一个issue评论吧，而且这样也会通过邮件通知，没有那种别人的个人博客的虚无缥缈的感觉。

所以这个莫名其妙的issue就出现了，感觉还挺有缘分的，所以这个issue也包含想认识一哈的目的，我还蛮有趣的，至少做朋友应该是不错的。

顺便一提，由于这是本仓库唯一一个issue，所以如果你想删除的话，所有者可以在这个issue界面的右下角找到”Delete issue“并点击删除。

**Comment by Summyj** [comment]
道理我都明白，怎么认识？(毕竟这是public的现在整个github都知道咱俩要认识了)

**Comment by BarryYan** [comment]
来吃瓜围观了🤓
